[in-review] Add credo to the project and:
elixirkoans/elixir-koans pull request #285
Opened 2023-11-09 19:58 UTC by imahmedismail

This PR involves the following changes:

- Add credo to the project and:
   - Run mix credo --all to identify possible code optimizations
   - Resolve most of the errors generated by credo such as:
     - Numbers larger than 9999 should be written with underscores: 58_127
     - Modules should have a @moduledoc tag
     - Comparison will always return true

2023-11-09 22:37 UTC, iamvery requested changes
This all seems pretty reasonable to me, and I don't have any strong feelings against Credo. There is one place that I think is a mistake (see requested change).

2023-11-09 22:37 UTC, iamvery commented on test/blanks_test.exs
> +    ast = quote do: assert true == false
```suggestion
    ast = quote do: assert ___ == ___
```

2023-11-10 08:20 UTC, imahmedismail commented on test/blanks_test.exs
> +    ast = quote do: assert true == false
This is done.

2023-11-10 13:09 UTC, iamvery commented
I added configuration for credo to run in CI using `--strict` mode and fixed the suggestions it made. Thanks for the idea and getting this started!

2023-11-10 13:11 UTC, merged